package com.winit.airarabia.webaccess;

public enum ServiceMethods
{
	WS_TEST,
	AIR_PORT_SDATA,
	AIR_AVAILABILITY,
	AIR_AVAILABILITY_RETURN,
	AIR_PRICEQUOTE,
	ANCILLARY_PRICEQUOTE,
	AIR_BAGGAGE_DETAILS,
	AIR_MEAL_DETAILS,
	AIR_SEAT_DETAILS,
	INSURANCE_QUOTE,
	HALA_REQ,
	AIR_BOOK,
	AIR_PNR,
	AIR_FLIGHT_SHEDULE,
	MODIFIED_RESQUERY,
	MODIFY_RESERVATION,
	LOG_PNR,
	MODIFY_PNR,
	WS_CITY,
	WS_NATIONALITIES,
	WS_COUNTRYISDCODES,
	WS_COUNTRYNAMES,
	WS_OFFICELOCATIONS,
	WS_LOGIN,
	WS_POSTER_DOWNLOAD,
	CURRENCY_CONVERSION_SERVICE,
	CANCEL_FLIGHT_CONFIRMATION,
	CANCEL_FLIGHT, MODIFY_BOOK
}
